#!/bin/bash
if [ $# -eq 0 ]; then
    echo "You have to set at least filename." 1>&2
    exit 1
elif [ $1 = '--test' ]; then
    echo "command is available"
    exit 0
elif [ -e $1 ]; then
    if [[ $1 = *.md ]]; then
        echo "input is markdown"
        curl https://api.github.com/markdown/raw \
            -X "POST" \
            -H "Content-Type: text/plain" \
            -d "$(cat $1)" > target_content
        sed -i -ze "s/\n//g" -e "s/\"/\\\\\\\\\\\\\"/g" target_content
    elif [[ $1 = *.xml ]]; then
        echo "input is xml"
        cat $1 > target_content
        sed -i -ze "s/\n//g" -e "s/\"/\\\\\\\\\\\\\"/g" target_content
    else
        sed -ze "s/\n/\\\n/g" $1 > target_content
    fi
else 
    echo "file is not found." 1>&2
    exit 1
fi

if  [ -e $2 ]; then
    COMMENT_ID=$2
else
    echo "insert commend_id" 1>&2
    exit 1

if [ $# -ge 3 ] && [ $3 = '--skip-token' ]; then
    echo "skip getting token."
else
    python /src/get_token.py
    export GITHUB_API_TOKEN=`cat /src/token.conf`
    rm /src/token.conf
fi

curl -X POST \
    -H "Authorization: token ${GITHUB_API_TOKEN}" \
    -H "Accept: application/json" \
    -H "Content-Type:application/json" \
    -d "{\"body\": \"$(cat target_content)\"}" \
    "https://api.github.com/repos/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}/issues/${DRONE_PULL_REQUEST}/comments/${COMMENT_ID}"

rm target_content

# TODO
# listでnoがあればupdate,なければpostが良さそう
# 初回POST時にidを受け取っておく(どこに保存するか)
# listで何か対応できそうか

