#!/bin/bash

if [ $# -ne 1 ]; then
    echo "input target file" 1>&2
    exit 1
elif [ $1 = '--test' ]; then
    echo "command is available"
    exit 0
elif [[ $1 = *.md ]]; then
    echo "input is markdown"
    curl https://api.github.com/markdown/raw \
        -X "POST" \
        -H "Content-Type: text/plain" \
        -d "$(cat $1)" > content.xml
    sed -i -ze "s/\n//g" -e "s/\"/\\\\\\\\\\\\\"/g" content.xml
    comment_filename=content.xml
else
    comment_filename=$1
    sed -i -ze "s/\n/\\\n/g" $comment_filename
fi

python /src/get_token.py
export GITHUB_API_TOKEN=`cat /src/token.conf`
rm /src/token.conf

curl -X POST \
    -H "Authorization: token ${GITHUB_API_TOKEN}" \
    -H "Accept: application/json" \
    -H "Content-Type:application/json" \
    -d "{\"body\": \"$(cat ${comment_filename})\"}" \
    "https://api.github.com/repos/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}/issues/${DRONE_PULL_REQUEST}/comments"

if [[ $1 = *.md ]]; then
    rm content.xml
fi
