#!/bin/bash
if [ $# -eq 0 ]; then
    echo "You have to set at least file or directory name." 1>&2
    exit 1
elif [ $1 = '--test' ]; then
    echo "command is available"
    exit 0
elif [ -e $1 ]; then
    python /src/get_token.py
    export GITHUB_API_TOKEN=`cat /src/token.conf`
    export REVIEWDOG_GITHUB_API_TOKEN=$GITHUB_API_TOKEN
    rm /src/token.conf

    echo $1

    # ここにpytest について書く
    #
    #
    #

    pr_comment comment --skip-token
    rm comment
    rm content
else 
    echo "file is not found." 1>&2
    exit 1
fi