#!/bin/bash

set -o errexit
set -o nounset

if [ $# -eq 0 ]; then
    echo "You have to set at least file or directory name." 1>&2
    exit 1
elif [ $1 = '--test' ]; then
    echo "command is available"
    exit 0
elif [ -e $1 ]; then
    python /src/module/gettoken.py
    export GITHUB_API_TOKEN=`cat /src/token.conf`
    export REVIEWDOG_GITHUB_API_TOKEN=$GITHUB_API_TOKEN
    rm /src/token.conf

    echo $1

    # ここにpytest について書く
    pytest --cov=$1 --cov-branch -v --cov-report=xml:pytest_raw.xml
    pycobertura show pytest_raw.xml > pytest_table
    touch comment
    {
        echo "## Test Coverage"
        echo "\`\`\`"
        cat pytest_table
        echo "\`\`\`"
    } > comment

    pr_comment comment --skip-token
    rm comment
    rm pytest_raw.xml
    rm pytest_table
else 
    echo "file is not found." 1>&2
    exit 1
fi
