#!/bin/bash

set -o errexit
set -o nounset

if [ $# -eq 0 ]; then
    echo "You have to set at least file or directory name." 1>&2
    exit 1
elif [ $1 = '--test' ]; then
    echo "command is available"
    exit 0
elif [ -e $1 ]; then
    python /src/module/gettoken.py
    export GITHUB_API_TOKEN=`cat /src/token.conf`
    export REVIEWDOG_GITHUB_API_TOKEN=$GITHUB_API_TOKEN
    rm /src/token.conf

    echo $1
    flake8 $1 | reviewdog -reporter="github-pr-review" -f=pep8 > content

    if [ ! -s content ]; then
        echo ":100: All OK!" > comment
    else
        lines=$(cat content | wc -l)
        echo "you have ${lines} warnings or errors on python style codes." > comment
        cat content >> comment
    fi

    pr_comment comment --skip-token
    rm comment
    rm content
else 
    echo "file is not found." 1>&2
    exit 1
fi

# reported by reviewdogなどで判定してコメントを消す。-> 新たにreviewdogでコメントさせる
