#!/bin/bash
export PRIVATE_KEY=$(gcloud secrets versions access latest --secret="mydog-private-key")
export APP_ID=$(gcloud secrets versions access latest --secret="mydog-app-id")
export INSTALLATION_ID=$(gcloud secrets versions access latest --secret="mydog-installation-id")
