---
kind: pipeline
name: default

# dev: &build



steps:
- name: mydog-dev
  image: docker:dind
  environment:
    DOCKER_USER:
      from_secret: username
    DOCKER_PASS:
      from_secret: dockerpw
  command:
    -ls -l \
    - echo $PATH
    - docker -v
    - docker images
    - &login echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    - make dev-release
  when:
    &dev-push
    branch:
      exclude:
        - master

# - name: mydog
#   <<: *build
#   command:
#     - *login
#     - make release

#   when:
#     &master-push
#     branch:
#       - master
#     event:
#       - push
