kind: pipeline
name: default

steps:
- name: mydog-python-dev
  &build .
  image: yashikab/drone-build
  environment:
    DOCKER_USER:
      from_secret: username
    DOCKER_PASS:
      from_secret: dockerpw
  command:
    - &login echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    - make dev-release
  when:
    &dev-push
    branch:
      exclude:
        - master

- name: mydog-python
  <<: *build
  command:
    - *login
    - make release

  when:
    &master-push
    branch:
      - master
    event:
      - push
