kind: pipeline
name: default

steps:
- name: mydog-python
  image: plugins/docker
  settings:
    username:
      from_secret: username
    password:
      from_secret: dockerpw
<<<<<<< HEAD
  settings:
    username: yashikab
    password: $DOCKER_PW
=======
>>>>>>> f46307f... fix5
    repo: yashikab/mydog
    tags: python-dev
  when:
    &dev-push
    branch:
      exclude:
        - master